### ISSUE TITLE
German Translation is missing

### ISSUE THREAD

**Issue by RainerBielefeld** [aljawaid/AgileIndicators#1]
I can do that until weekend – if nobody is faster than me.

**Comment by aljawaid** [comment]
If I create the template file, can you update it into German?  I just use Google but its a lot faster for a german speaker to translate.

**Comment by aljawaid** [comment]
I have added the template, I will update the string shortly

**Comment by RainerBielefeld** [comment]
Thx

**Comment by RainerBielefeld** [comment]
I downloaded "translations.php" and contribute German Sentences, soon.

**Comment by RainerBielefeld** [comment]
I did a quick test with the patch in the master branch:  
![grafik](https://user-images.githubusercontent.com/11803749/198243486-de2efec6-d997-428f-a6d2-8b099d80797c.png)
Works fine!

**Comment by RainerBielefeld** [comment]
And I haven't a clue how to do a Pull Request for the patch.
