### ISSUE TITLE
 AgileIndicators has gone from Pinboard, List and Overview View

### ISSUE THREAD

**Issue by RainerBielefeld** [aljawaid/AgileIndicators#3]
In all my 3 KANBOARD installations this evening Sidebars have gone from Pinboard, List and Overview View.
Still visible  in Projects Overview.
* Has there been some automatic update or so?
* Bug or feature?

**Comment by aljawaid** [comment]
- No updates since v1.0
- - The plugin only shows on the dashboard and the task page... it was designed for them locations only.
