### ISSUE TITLE
Untranslated String shown because of Syntax error?

### ISSUE THREAD

**Issue by RainerBielefeld** [aljawaid/AgileIndicators#5]
# Untranslated String  
view in German Localization de_DE:
![](https://imgur.com/3Ke8510.png)  
  
# I don't know wether related:

## Text Comparison:

```
en_GB:
<?php
return array(

de_DE:
<?php
return array(
``` 

 
Seems to be identical
  
## View in GitHub:  

| en_GB: | de_DE: |
|---|---|
| ![](https://imgur.com/h8qHnuq.png) | ![](https://imgur.com/i7GoJmU.png) |
 
de_DE with strange yellow line background and additional space at the left

---
* I can simply try to repair, but wanted to hear your opinion before.
* In GitHub Edit Mode I can't see anything suspicious

**Comment by RainerBielefeld** [comment]
Should have told: In my KANBOARD installation the string is translated to German!

**Comment by aljawaid** [comment]
everything seems fine on this side... I dont think it is related to the plugin.

Delete the plugin and see if the problem is resolved.

**Comment by RainerBielefeld** [comment]
Well, I already uninstalled and reinstalled the Plugin yesterday via Plugins Manager / Plugin Directory.  
Now again, and strange effect, 
* in my main Installation only en_GV becomes installed. 
* Folder de_DE is missing  

Tried again with a different KANBOARD installation on the same server. Same effect, **only en_GB comes installed**.

**Comment by aljawaid** [comment]
> Well, I already uninstalled and reinstalled the Plugin yesterday via Plugins Manager / Plugin Directory.  
> Now again, and strange effect, 
> * in my main Installation only en_GV becomes installed. 
> * Folder de_DE is missing  
> 
> Tried again with a different KANBOARD installation on the same server. Same effect, **only en_GB comes installed**. 

```
  'Agile Indicators displays the measurements for Task Priorities and Task Complexities in an easy to use general scale. Task Priorities are scaled between P1 and P5 whilst Task Complexities are scored as 0-50.' => '"Agile Indicators" zeigt die Einstufung von Aufgabenpriorität und Aufgabenkomplexität in einer einfach zu verwendenden allgemeinen Skala an. Die Aufgabenpriorität wird zwischen P1 und P5 skaliert, während die Aufgabenkomplexität mit 0-50 bewertet wird.',
```
Try removing the quotes. Your string contains `"Agile Indicators"` but try changing to `AgileIndicators` (no quotes)

**Comment by RainerBielefeld** [comment]
You are right, the quotes around the wrong name are nonsense. 
I did acorrection (see pull request for afba502) and will try tomorrow or so if that really heals the Untranslated String issue

**Comment by RainerBielefeld** [comment]
Well this syntax-error -Text Comparison thingy is nonsense. I simply clicked the line number, what made it marked yellow.
