### ISSUE TITLE
Untranslated String shown using de_DE

### ISSUE THREAD

**Issue by RainerBielefeld** [aljawaid/AgileIndicators#7]
This one is a followup to "Untranslated String shown because of Syntax error? #5":
![](https://camo.githubusercontent.com/aa0c967564b8c94fbf9b3cb93b25db6ffad54ff561fbe9977deabb56d7080706/68747470733a2f2f696d6775722e636f6d2f334b65383531302e706e67)

I found the real reason for the untranslated string problem:
In 
\Template\dashboard\sidebar.php
and 
\Template\task\sidebar.php
The used string is
`
'No external resources'
`
but in translations.php it is
`'No external resource'`

See the missing "s" at the end in translations.php! I think because of that difference to translation can be found.

I tested with deleting the tailing "s" in both sidebar.php, afterwards translation in my KANBOARD installation worked fine.

But I think the more plausible solution is to add the tailing "s" in the translations.php files.

Your opinion?

**Comment by aljawaid** [comment]
cool I will fix this and release an updated version later this week
